before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
    main: ./cmd/gtokenserver
archives:
  - format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
