name: Release ikedam/gtokenserver
on:
  push:
    tags:
      - v*
env:
  DOCKERHUB_REPOSITORY: ikedam/gtokenserver
jobs:
  release-github:
    name: Release to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Required for changelog
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-docker:
    name: Publish to dockerhub and github packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t gtokenserver \
            --build-arg VERSION=${GITHUB_REF##*/} \
            --build-arg COMMIT=${GITHUB_SHA} \
            .
      - name: Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login docker.pkg.github.com -u "${GITHUB_REPOSITORY%/*}" --password-stdin
      - name: Deploy
        run: |
          TAG=${GITHUB_REF##*/}
          docker tag gtokenserver "${DOCKERHUB_REPOSITORY}:${TAG}"
          docker tag gtokenserver "${DOCKERHUB_REPOSITORY}:latest"
          docker tag gtokenserver "docker.pkg.github.com/${GITHUB_REPOSITORY}/gtokenserver:${TAG}"
          docker tag gtokenserver "docker.pkg.github.com/${GITHUB_REPOSITORY}/gtokenserver:latest"
          docker push "${DOCKERHUB_REPOSITORY}:${TAG}"
          docker push "${DOCKERHUB_REPOSITORY}:latest"
          docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/gtokenserver:${TAG}"
          docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/gtokenserver:latest"
